# Generated by Django 5.1.4 on 2026-06-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedaddress',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savedaddress',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
