# Generated by Django 5.1.4 on 2026-06-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('verification', 'Verification'), ('password_reset', 'Password Reset'), ('email_change', 'Email Change')], default='verification', max_length=20),
        ),
    ]
