# Generated by Django 5.1.4 on 2026-08-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_use_email_as_username_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_auth_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Social Auth ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_auth_provider',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('facebook', 'Facebook'), ('apple', 'Apple')], max_length=20, null=True, verbose_name='Social Auth Provider'),
        ),
    ]
