# Generated by Django 5.1.4 on 2026-06-07 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='engine_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.enginetype', verbose_name='Engine Type'),
        ),
        migrations.AddField(
            model_name='service',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.vehicletype', verbose_name='Vehicle Type'),
        ),
    ]
