# Generated by Django 5.1.4 on 2026-06-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_appsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='content',
            field=models.TextField(blank=True, help_text='Content of the setting (HTML allowed)'),
        ),
    ]
