# Generated by Django 5.1.4 on 2026-06-14 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
        ('services', '0002_service_engine_type_service_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='service_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='service_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='service_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='service_radius_km',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='providers.providerprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'unique_together': {('provider', 'service')},
            },
        ),
    ]
