# Generated by Django 5.1.4 on 2026-06-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_providerprofile_service_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='document_verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text='Verification status of provider documents (ID, insurance, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='documents_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='documents_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
