# Generated by Django 5.1.4 on 2026-08-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_providerprofile_document_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='stripe_account_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='stripe_onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
