# Generated by Django 5.1.4 on 2026-06-05 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('providers', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_address', models.TextField()),
                ('service_city', models.CharField(blank=True, max_length=100)),
                ('service_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('service_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('schedule_type', models.CharField(choices=[('now', 'Now'), ('scheduled', 'Scheduled')], default='now', max_length=10)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('service_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('vehicle_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('dirt_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('distance_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('engine_discount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tip_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('en_route', 'En Route'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=15)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='customers.customerprofile')),
                ('dirt_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.dirtlevel')),
                ('payment_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.paymentcard')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='providers.providerprofile')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='BookingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='booking_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='bookings.booking')),
            ],
        ),
    ]
