# Generated by Django 5.1.4 on 2026-06-20 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_service_latitude_and_more'),
        ('providers', '0002_providerprofile_service_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejected_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='bookings.booking')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_rejections', to='providers.providerprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['booking'], name='bookings_bo_booking_47d37e_idx'), models.Index(fields=['provider'], name='bookings_bo_provide_0ca008_idx')],
                'unique_together': {('booking', 'provider')},
            },
        ),
    ]
